sonar.organization=gggard
sonar.projectKey=gggard_orbital

sonar.sources=src,ui/src
sonar.tests=tests,ui/src
sonar.test.inclusions=ui/src/**/*.test.ts,ui/src/**/*.test.tsx
sonar.exclusions=ui/.next/**,ui/node_modules/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=ui/coverage/lcov.info
